# Site settings
title: Android - getmdl.io
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://portal-easy.codio.io:4000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

excerpt_separator: <!--more-->
images_path: /assets/images/
# Build settings
markdown: kramdown
# Compress layout - Settings
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: true
  ignore:
    envs: [local]
    
pluginsSourceFile: pluginsSourceFiles

page_gen:
  - data: 'productsYML'
    template: 'product'
    name: 'sku'
    dir: 'products'

# Build settings
markdown: kramdown



collections:
  docs:
    output: true
    permalink: /docs/:path/
  components:
    output: true
    permalink: /components/:path/
  blog:
    output: true
    permalink: /blog/:path/
  work:
    output: true
    permalink: /work/:path/
